### ISSUE TITLE
The code :pru_rpmsg_send_large_buffer()  not found  here? 

### ISSUE THREAD

**Issue by eziohzy** [ZeekHuge/BeagleScope#4]
Hi,
Following your wonderful post at https://groups.google.com/forum/#!topic/beagleboard-gsoc/aSFxmYjrWuA. At week 10,you mentioned pru_rpmsg_send_large_buffer() , that's what I want ,please help me .^_^

**Comment by zeekhuge** [comment]
Hello !
Thank you for the complement.
The `pru_rpmsg_send_large_buffer()` actually uses core methods and using it, you can send 440 byte large buffer at once.

You can checkout the code here - https://github.com/ZeekHuge/BeagleScope/blob/port_to_4.4.12-ti-r31%2B/firmware/main_pru0.c#L93

PS : Please close the issue if this resolves your query.

**Comment by eziohzy** [comment]
Thanks for reply!!!
